name: docs_pages_workflow
 
# execute this workflow automatically when a we push to main
on:
  push:
    branches: [ main ]
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
 
    steps:
 
    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEBIAN_FRONTEND: nonintercative
        DEBCONF_NONINTERACTIVE_SEEN: true
      run: |
        apt-get update
        apt-get install -y git pip
        pip install git+https://github.com/themasmedia/mas-blender.git@main#egg=mas-blender
        git clone --depth 1 "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      shell: bash
 
    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "docs/buildDocs.sh"
      shell: bash